language: ruby
rvm:
  - 2.4

cache: bundler
script: bundle exec jekyll serve --baseurl "" --detach && bundle exec htmlproofer ./_site --disable-external --empty-alt-ignore

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true JEKYLL_ENV=production
