
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://chirimen-oh.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl:

# Google tracking id to track your visitors

google-tracking-id: "UA-75123287-2"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "CHIRIMEN Open Hardware"
title: "CHIRIMEN Open Hardware"
description: "CHIRIMEN Open Hardware is a community-driven, is an open hardware project."
keywords: "chirimen, iot, wot, javascript"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/favicon.ico"

#background-img: "../img/chirimen_2.gif"
background-img: "../img/BGJ.jpg"


##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Welcome to Open Hard ware to the world !"
  - text: "What do you want to achieve the world with CHIRIMEN?"
  - text: "CMN2015-1  Raspberry Pi  TY51822r3  micro:bit  Node.js"

me-img: "/img/browser_300.png"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web/android-icon-36x36.png"
icon-48p: "/img/web/android-icon-48x48.png"
icon-72p: "/img/web/android-icon-72x72.png"
icon-96p: "/img/web/android-icon-96x96.png"
icon-144p: "/img/web/android-icon-144x144.png"
icon-192p: "/img/web/android-icon-192x192.png"

########
# Blog #
########

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "chirimen-oh"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/browser_300.png"
    date: "October 10 2018"
    description: "CHIRIMEN for Raspberry Pi 3 Ver.2018/10/10 released."
  - image: "/img/browser_300.png"
    date: "November 2 2017"
    description: "CHIRIMEN for Raspberry Pi 3 released."
  - image: "/img/browser_300.png"
    date: "March 1 2017"
    description: "New firmware had released."
  - image: "/img/browser_300.png"
    date: "February 4 2017"
    description: "CHIRIMEN touch & try events."
  - image: "/img/browser_300.png"
    date: "January 9 2017"
    description: "CHIRIMEN Board Echigo Rev.1 was sold-out!"
  - image: "/img/browser_300.png"
    date: "December 31 2016"
    description: "CHIRIMEN Board had certified by the OSHA. "
  - image: "/img/browser_300.png"
    date: "September 17 2016"
    description: "The Sale Memorial Day Event CHIRIMEN Board hands-on"
  - image: "/img/browser_300.png"
    date: "August 08 2016"
    description: "Released CHRIMEN Board first firmware image !!!"
  - image: "/img/browser_300.png"
    date: "August 06 2016"
    description: "Sale Of CHIRIMEN Board Started By Switch Science !!!"
  - image: "/img/browser_300.png"
    date: "April 30 2016"
    description: "CHIRIMEN's day"

# First image of the Timeline

timeline-img: "/img/browser_300.png"

###########
# Contact #
###########

email: "chirimen.open.hardware@gmail.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "CHIRIMEN COMING SOON"
author_blurb_image: "/img/browser_300.png"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://www.facebook.com/groups/chirimen/"
  - title: "twitter"
    url: "https://twitter.com/chirimen_oh"
  - title: "github"
    url: "https://github.com/chirimen-oh"
  - title: "slack"
    url: "https://docs.google.com/forms/d/1GzkGfCcsRn4A6-uHPsLu2LszkqKcNJ3sFI4XRishHsE/viewform"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/browser_300.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  News: 'news'
  About: 'about'
  Documents/Downloads: 'documents'
  Tutorial: 'tutorial'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts", 'Gemfile','Gemfile.lock','Rakefile','vendor']

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jemoji
